services:
  - type: web
    name: financial-aggregator-backend
    env: go
    buildCommand: go build -o main ./apps/backend
    startCommand: ./main
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars: []

  - type: web
    name: financial-aggregator-frontend
    env: node
    buildCommand: |
      npm install -g pnpm
      pnpm install
      pnpm --filter frontend build
    startCommand: bash -lc "cd apps/frontend && npx vite preview --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://financial-aggregator-backend.onrender.com
        # Replace with your actual backend URL after the backend service is created
